services:
  - type: web
    name: test_guru
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: ./bin/render-build.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: test_guru_database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: true
      - key: RAILS_ENV
        value: production

databases:
  - name: test_guru_database
    plan: free
    postgresVersion: 14
